server:
  port: 9193
spring:
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:~/userData
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
  application:
    name: IDENTITY-SERVICE