server:
  port: 9192
spring:
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:~/testdb
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
  application:
    name: ORDER-SERVICE
logging:
  file.name: C:/Users/sapna.g.sharma/Downloads/logs/services.log
management:
  health:
    circuit-breakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
resilience4j:
  circuit breaker:
    instances:
      orderService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 5
        failureRateThreshold: 50
        minimumNumberOfCalls: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      orderService:
        maxAttempts: 5
        waitDuration: 10s